<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="support_wheels" params="parent">

  <!-- Right Support Wheel -->
  <link name="wheel_right_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.766" />
      <inertia ixx="0.002" ixy="0.0000001352" ixz="0.00000005832"
		 iyy="0.004" iyz="0.00000005457" izz="0.002" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://minireach_description/meshes/support_wheel/support_wheel.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${support_wheel_radius}" length="${support_wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0 ${-support_wheel_separation / 2} 0" rpy="${-90.0 * deg_to_rad} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>


  <!-- Left Support Wheel -->
  <link name="wheel_left_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.766" />
      <inertia ixx="0.002" ixy="0.0000001352" ixz="0.00000005832"
		 iyy="0.004" iyz="0.00000005457" 
		 izz="0.002" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://minireach_description/meshes/support_wheel/support_wheel.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${support_wheel_radius}" length="${support_wheel_width}"/>
      </geometry>
    </collision>
  </link>
            
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0 ${support_wheel_separation / 2} 0" rpy="${90.0 * deg_to_rad} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Transmissions -->
  <!-- right and left wheel don't get published on tf without transmission interfaces -->

  <transmission name="wheel_left_tran">
   <type>transmission_interface/SimpleTransmission</type>
   <joint name="wheel_left_joint">
     <hardwareInterface>EffortJointInterface</hardwareInterface>
   </joint>
   <actuator name="motor2">
     <hardwareInterface>EffortJointInterface</hardwareInterface>
     <mechanicalReduction>1</mechanicalReduction>
   </actuator>
  </transmission>

  <transmission name="wheel_right_tran">
   <type>transmission_interface/SimpleTransmission</type>
   <joint name="wheel_right_joint">
     <hardwareInterface>EffortJointInterface</hardwareInterface>
   </joint>
   <actuator name="motor3">
     <hardwareInterface>EffortJointInterface</hardwareInterface>
     <mechanicalReduction>1</mechanicalReduction>
   </actuator>
  </transmission>


  <!-- Gazebo extentions -->
  <gazebo reference="wheel_right_link">
    <material>Gazebo/Orange</material>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.003</minDepth>
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>

  <gazebo reference="wheel_left_link">
    <material>Gazebo/Orange</material>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.003</minDepth>
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>


  </xacro:macro>
</robot>

